services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: eduexce-ngrok
    depends_on:
      - api
    env_file:
      - .env.development
    command: ["ngrok", "http", "api:3333"]
    ports:
      - "4040:4040"
    restart: unless-stopped
